import {faCartPlus, faCartShopping, faHandMiddleFinger, IconDefinition} from "@fortawesome/free-solid-svg-icons";
import { faUser,  // 'user-circle'
  faUserCheck,    // 'user-check'
  faUserEdit,     // 'user-edit'
  faUserPlus,     // 'user-plus'
  faUserMinus,    // 'user-minus'
  faUsers,        // 'users'
  faHome,         // 'home'
  faCompass,      // 'compass'
  faMap,          // 'map'
  faLocationArrow,// 'location-arrow'
  faCog,          // 'cog'
  faTools,        // 'tools'
  faWrench,       // 'wrench'
  faEdit,         // 'edit'
  faTrash,        // 'trash'
  faPlus,         // 'plus'
  faMinus,        // 'minus'
  faEnvelope,     // 'envelope'
  faComment,      // 'comment'
  faComments,     // 'comments'
  faBell,         // 'bell'
  faPaperPlane,   // 'paper-plane'
  faCamera,       // 'camera'
  faVideo,        // 'video'
  faFileAlt,      // 'file-alt'
  faFileDownload, // 'file-download'
  faFileUpload,   // 'file-upload'
  faLock,         // 'lock'
  faUnlock,       // 'unlock'
  faShieldAlt,    // 'shield-alt'
  faKey,
  faChevronDown,
  faSearch } from "@fortawesome/free-solid-svg-icons";
export const fontAwesomeIcons:IconDefinition[]=[
  faUser,   // 'user'
  faUserCheck,    // 'user-check'
  faUserEdit,     // 'user-edit'
  faUserPlus,     // 'user-plus'
  faUserMinus,    // 'user-minus'
  faUsers,        // 'users'
  faHome,         // 'home'
  faCompass,      // 'compass'
  faMap,          // 'map'
  faLocationArrow,// 'location-arrow'
  faCog,          // 'cog'
  faTools,        // 'tools'
  faWrench,       // 'wrench'
  faEdit,         // 'edit'
  faTrash,        // 'trash'
  faPlus,         // 'plus'
  faMinus,        // 'minus'
  faEnvelope,     // 'envelope'
  faComment,      // 'comment'
  faComments,     // 'comments'
  faBell,         // 'bell'
  faPaperPlane,   // 'paper-plane'
  faCamera,       // 'camera'
  faVideo,        // 'video'
  faFileAlt,      // 'file-alt'
  faFileDownload, // 'file-download'
  faFileUpload,   // 'file-upload'
  faLock,         // 'lock'
  faUnlock,       // 'unlock'
  faShieldAlt,    // 'shield-alt'
  faKey, // 'key'
  faHandMiddleFinger,
  faCartPlus,
  faCartShopping,
  faChevronDown,
  faSearch
]
